const translations = {
    es: {
        /* Topbar */
        daysAndHours: "Lunes - Viernes : 09 AM - 06 PM",

        /* Navbar */
        home: "Inicio",
        aboutUs: "Nosotros",
        ourProducts: "Nuestros Productos",
        pages: "Páginas",
        features: "Características",
        appointment: "Hacer Cita",
        ourTeam: "Nuestro Equipo",
        testimonial: "Testimonial",
        idioms: "Idiomas",
        contact: "Contacto",

        /* Carousel  */
        welcomeToEQUIALUM: "Bienvenidos a EQUIALUM",
        leadersInAluminumFoundry: "Líderes en Fundición de Aluminio",
        innovationAndQualityInEveryForm: "Innovación y Calidad en Cada Forma",
        commercial: "Comercial",
        industrial: "Industrial",
        moreDetails: "Más detalles",

        years: "Años",
        experience: "Experiencia",

        /* About */
        talkAboutUs: "Sobre nosotros",
        innovationAndQualityWithinYourReach: "Innovación y Calidad a tu Alcance",
        about1: "Somos una empresa mexicana que se destaca por su alta calidad en servicios integrales de fundición y comercialización de metales",
        about2: "Mejoramos continuamente nuestro sistema de gestión de calidad, respetamos el medio ambiente cumpliendo con el marco legal e implementamos continuamente mejoras en los procesos anticipándonos a las necesidades de nuestros colaboradores, proveedores y clientes, lo que nos convierte en una empresa progresista y en constante crecimiento",
        punctualityInServices: "Puntualidad en los servicios",
        excellentService: "Excelente servicio",
        verifiedProfessionals: "Profesionales verificados",
        equialumPhilosophy: "Filosofia de EQUIALUM",
        equialumCertificate: "Certificado EQUIALUM S.A. de C.V.",

        /* Facts */
        industry: "Industria",
        readMore: "LEER MÁS",
        automotive: "Automotriz",
        fact1: "EQUIALUM suministra productos de alta calidad, mejorando la eficiencia y sostenibilidad de los vehículos",
        aerospace: "Aeroespacial",
        fact2: "Proporcionamos productos de alta calidad que optimizan el rendimiento y la seguridad de las aeronaves",
        electronics: "Electrónica",
        fact3: "Ofrecemos productos de alta calidad que facilitan la fabricación de componentes electrónicos fiables y eficientes",
        construction: "Construcción",
        fact4: "Suministramos productos de aluminio que mejoran la durabilidad y estética de las estructuras y acabados",

        /* Automotive Industry - Facts */
        automotiveIndustrySubTitle: "Aluminio de Calidad para Vehículos de Alta Prestación",
        automotiveIndustryTitle: "Automotriz",
        automotiveIndustryDescription: "EQUIALUM se enorgullece de ser un proveedor confiable para la industria automotriz, ofreciendo aluminio de alta calidad que contribuye a la fabricación de vehículos más eficientes y seguros",
        automotiveIndustryDescription1: "Reducción de Peso",
        automotiveIndustryDescription2: "El aluminio de EQUIALUM permite la fabricación de componentes más livianos, disminuyendo el peso total del vehículo y mejorando la eficiencia del combustible",
        automotiveIndustryDescription3: "Durabilidad",
        automotiveIndustryDescription4: "Nuestro aluminio ofrece una alta resistencia a la corrosión, asegurando la longevidad de las partes automotrices, incluso en condiciones extremas",
        automotiveIndustryDescription5: "Eficiencia Energética",
        automotiveIndustryDescription6: "Al reducir el peso de los vehículos, nuestro aluminio contribuye a menores emisiones de CO2 y mayor eficiencia energética, alineándose con las tendencias de sostenibilidad",
        automotiveIndustryDescription7: "Flexibilidad en Diseño",
        automotiveIndustryDescription8: "La maleabilidad del aluminio de EQUIALUM permite a los diseñadores automotrices innovar con formas complejas y ligeras, mejorando la estética y funcionalidad de los vehículos",
        automotiveIndustryDescription9: "Cumplimiento Normativo",
        automotiveIndustryDescription10: "Nuestros productos cumplen con estrictos estándares internacionales, garantizando la seguridad y calidad en aplicaciones automotrices",
        automotiveIndustryDescription11: "Producción Sostenible",
        automotiveIndustryDescription12: "EQUIALUM utiliza procesos de producción sostenibles, minimizando el impacto ambiental y promoviendo una cadena de suministro responsable",
        automotiveIndustrySubDescription: "El aluminio de EQUIALUM es fundamental en la construcción de vehículos que buscan el equilibrio entre rendimiento, seguridad y sostenibilidad",

        /* Aerospace Industry - Facts */
        aerospaceIndustrySubTitle: "Materiales Avanzados para la Aviación Moderna",
        aerospaceIndustryTitle: "Aeroespacial",
        aerospaceIndustryDescription: "EQUIALUM es un socio clave en la industria aeroespacial, proporcionando aluminio de alta calidad que es esencial para la fabricación de aeronaves avanzadas y componentes aeroespaciales",
        aerospaceIndustryDescription1: "Optimización del Rendimiento",
        aerospaceIndustryDescription2: "Nuestro aluminio ayuda a optimizar el rendimiento de las aeronaves al reducir su peso y mejorar la aerodinámica",
        aerospaceIndustryDescription3: "Durabilidad Extrema",
        aerospaceIndustryDescription4: "Los productos de aluminio de EQUIALUM están diseñados para soportar las condiciones extremas del entorno aeroespacial, desde altas altitudes hasta temperaturas extremas",
        aerospaceIndustryDescription5: "Facilidad de Mantenimiento",
        aerospaceIndustryDescription6: "El aluminio de alta calidad reduce los costos de mantenimiento al ser resistente y fácil de trabajar, prolongando la vida útil de las aeronaves",
        aerospaceIndustryDescription7: "Seguridad Garantizada",
        aerospaceIndustryDescription8: "Los componentes fabricados con nuestro aluminio ofrecen mayor seguridad en vuelos, cumpliendo con estrictos protocolos de seguridad aeroespacial",
        aerospaceIndustryDescription9: "Innovación en Diseño",
        aerospaceIndustryDescription10: "EQUIALUM facilita la innovación en la industria aeroespacial, permitiendo el desarrollo de diseños aerodinámicos más avanzados y eficientes",
        aerospaceIndustryDescription11: "Fiabilidad en la Cadena de Suministro",
        aerospaceIndustryDescription12: "Con un suministro constante y confiable, EQUIALUM apoya la producción continua y sin interrupciones en la industria aeroespacial",
        aerospaceIndustrySubDescription: "El aluminio de EQUIALUM es fundamental en la creación de aeronaves más seguras, ligeras y eficientes, respaldando los avances tecnológicos en la industria aeroespacial",

        /* Electronics Industry - Facts */
        electronicsIndustrySubTitle: "Aluminio de Precisión para la Innovación en la Industria Electrónica",
        electronicsIndustryTitle: "Electrónica",
        electronicsIndustryDescription: "EQUIALUM ofrece aluminio de alta calidad que es esencial para el desarrollo y producción de dispositivos electrónicos avanzados, aportando precisión y confiabilidad",
        electronicsIndustryDescription1: "Disipación de Calor",
        electronicsIndustryDescription2: "Nuestro aluminio es ideal para componentes electrónicos, ya que facilita una eficiente disipación de calor, prolongando la vida útil de los dispositivos",
        electronicsIndustryDescription3: "Ligereza y Resistencia",
        electronicsIndustryDescription4: "El aluminio de EQUIALUM proporciona una estructura robusta y ligera para carcasas y componentes, sin añadir peso innecesario a los dispositivos electrónicos",
        electronicsIndustryDescription5: "Maleabilidad para Diseño",
        electronicsIndustryDescription6: "Gracias a su maleabilidad, nuestro aluminio permite la fabricación de diseños complejos y precisos, adaptándose a las necesidades de la tecnología moderna",
        electronicsIndustryDescription7: "Conductividad Eléctrica",
        electronicsIndustryDescription8: "El aluminio que ofrecemos asegura una excelente conductividad eléctrica, ideal para circuitos y otros componentes críticos en la electrónica",
        electronicsIndustryDescription9: "Compatibilidad con Microelectrónica",
        electronicsIndustryDescription10: "EQUIALUM suministra aluminio compatible con la miniaturización, clave para la fabricación de dispositivos electrónicos compactos y eficientes",
        electronicsIndustryDescription11: "Calidad Consistente",
        electronicsIndustryDescription12: "Nuestro aluminio cumple con los más altos estándares de la industria, garantizando la calidad y fiabilidad en cada producto electrónico",
        electronicsIndustrySubDescription: "El aluminio de EQUIALUM impulsa la innovación en la industria electrónica, proporcionando materiales que mejoran la eficiencia y rendimiento de los dispositivos",

        /* Construction Industry - Facts */
        constructionIndustrySubTitle: "Aluminio de Vanguardia para Proyectos de Construcción",
        constructionIndustryTitle: "Construcción",
        constructionIndustryDescription: "EQUIALUM se posiciona como un aliado clave en la industria de la construcción, ofreciendo aluminio que aporta durabilidad, eficiencia y estilo en proyectos arquitectónicos modernos",
        constructionIndustryDescription1: "Durabilidad Superior",
        constructionIndustryDescription2: "Nuestro aluminio es resistente a la corrosión y al desgaste, asegurando estructuras duraderas y de bajo mantenimiento en la construcción",
        constructionIndustryDescription3: "Ligereza y Resistencia",
        constructionIndustryDescription4: "El aluminio de EQUIALUM combina ligereza con alta resistencia, permitiendo la construcción de edificaciones más seguras y sostenibles",
        constructionIndustryDescription5: "Versatilidad de Diseño",
        constructionIndustryDescription6: "Con nuestro aluminio, arquitectos e ingenieros pueden crear diseños innovadores y estéticamente atractivos, sin comprometer la funcionalidad o seguridad",
        constructionIndustryDescription7: "Eficiencia Energética",
        constructionIndustryDescription8: "Nuestro aluminio contribuye a la eficiencia energética en edificios, mejorando el aislamiento térmico y reduciendo el consumo energético",
        constructionIndustryDescription9: "Facilidad de Instalación",
        constructionIndustryDescription10: "Nuestros productos de aluminio son fáciles de trabajar e instalar, lo que agiliza los tiempos de construcción y reduce costos",
        constructionIndustryDescription11: "Cumplimiento Normativo",
        constructionIndustryDescription12: "EQUIALUM asegura que su aluminio cumple con los estándares de calidad y seguridad exigidos por la industria de la construcción",
        constructionIndustrySubDescription: "El aluminio de EQUIALUM es esencial para proyectos de construcción innovadores, ofreciendo soluciones que combinan resistencia, eficiencia y sostenibilidad",

        /* Features */
        becauseOur: "¿Por qué elegirnos?",
        features1: "Excelencia en Aluminio para Cada Industria",
        featuresDescription: "En EQUIALUM, nos destacamos por ofrecer productos de aluminio de la más alta calidad, respaldados por un compromiso con la innovación y la excelencia. Nuestra experiencia y atención al detalle aseguran soluciones personalizadas que cumplen con los más exigentes estándares industriales, garantizando resultados excepcionales en cada proyecto",
        bigQuality: "Gran calidad de productos",
        features2: "Productos de aluminio de alta pureza y resistencia, elaborados con los más estrictos estándares de control de calidad",
        moreThan12Years: "Más de 20 años de experiencia profesional",
        features3: "Adopción de tecnologías avanzadas y procesos innovadores para optimizar la producción y ofrecer soluciones a medida",
        continuousInnovation: "Innovación Continua",
        features4: "Atención al cliente excepcional y adaptabilidad para satisfacer las necesidades específicas de cada industria",
        environmentalCommitment: "Compromiso Ambiental",
        features5: "Prácticas sostenibles y reciclaje de aluminio que contribuyen a la reducción del impacto ambiental en todos los procesos",

        /* Products */
        productsTitle: "Soluciones de Aluminio de Alta Calidad",
        saw: "Lingotes/SAW",
        productsDescription1: "Nuestros lingotes de aluminio destacan por su alta pureza y calidad constante, perfectos para una variedad de aplicaciones industriales",
        bars: "Barras",
        productsDescription2: "Nuestras barras de aluminio ofrecen durabilidad y versatilidad, adecuadas para múltiples aplicaciones industriales",
        cones: "Conos",
        productsDescription3: "Nuestros conos de aluminio son robustos y precisos, ideales para aplicaciones que requieren resistencia y exactitud",
        liquid: "Liquido",
        productsDescription4: "Nuestro aluminio líquido se entrega con alta pureza y consistencia, ideal para fundición y procesos de moldeo",
        scrap: "Scrap",
        productsDescription5: "Nuestro scrap de aluminio es eficiente y ecológico, ideal para reciclaje y reutilización",
        innovation: "Innovación",
        productsDescription6: "Empleamos equipos y máquinas de vanguardia para garantizar procesos de producción precisos y eficientes",

        /* Manufacturing - Products */
        manufacturingSubTitle: "Fabricación",
        manufacturingTitle: "Proceso de Producción",
        manufacturingDescription: "Contamos con un meticuloso proceso de producción, donde combinamos tecnología avanzada y experiencia para crear productos de aluminio de alta calidad. Desde la materia prima hasta el producto final, cada etapa está diseñada para garantizar precisión y excelencia",
        manufacturingDescription1: "Cada fase de nuestro proceso, desde la fundición hasta el acabado, es supervisada por expertos para asegurar que nuestros productos cumplan con los más altos estándares de la industria. Nuestro enfoque en la eficiencia y la calidad nos permite ofrecer soluciones que superan las expectativas de nuestros clientes",

        /* Ingots/SAW - Product */
        ingotTitle: "Pureza y Precisión para Aplicaciones Industriales",
        ingotDescription: "El lingote/SAW de aluminio de EQUIALUM es un producto de alta calidad diseñado para satisfacer las demandas exigentes de diversas aplicaciones industriales. Fabricado a partir de aluminio de primera fusión, nuestros lingotes se caracterizan por su pureza y consistencia excepcionales, lo que asegura un rendimiento superior en cualquier proceso de fabricación",
        ingotFeauresTitle: "Características Destacadas",
        ingotFeauresDescription1: "Alta Pureza y Calidad Constante",
        ingotFeauresDescription2: "Nuestros lingotes de aluminio están fabricados con un contenido de alta pureza, garantizando un rendimiento excepcional y fiabilidad en aplicaciones industriales. Este nivel de pureza asegura que cada lingote cumple con los estándares más exigentes de calidad",
        ingotFeauresDescription3: "Diversidad de Tamaños y Formatos",
        ingotFeauresDescription4: "Ofrecemos lingotes en una variedad de tamaños y formatos estandarizados para adaptarse a diversos procesos industriales. Esta flexibilidad permite una integración más eficiente en diferentes aplicaciones, optimizando la producción",
        ingotFeauresDescription5: "Control de Calidad Rigurosos",
        ingotFeauresDescription6: "Cada lingote pasa por estrictos controles de calidad, incluyendo pruebas químicas y físicas, para asegurar que cumple con especificaciones internacionales. Esto garantiza un producto fiable y de alto rendimiento",
        ingotFeauresDescription7: "Sostenibilidad y Eficiencia",
        ingotFeauresDescription8: "Implementamos prácticas sostenibles y reciclaje eficiente en la producción de nuestros lingotes, minimizando el impacto ambiental y mejorando la rentabilidad de nuestros clientes mediante procesos optimizados",
        ingotBenefitsTitle: "Beneficios",
        ingotBenefitsDescription1: "Rendimiento Óptimo",
        ingotBenefitsDescription2: "La alta pureza y consistencia de nuestros lingotes aseguran un rendimiento superior en procesos de fundición y manufactura, reduciendo defectos y mejorando la durabilidad de los productos finales",
        ingotBenefitsDescription3: "Eficiencia en Procesos",
        ingotBenefitsDescription4: "El formato y calidad de nuestros lingotes permiten un procesamiento más eficiente y económico, optimizando tiempos de producción y reduciendo costos operativos",
        ingotBenefitsDescription5: "Sostenibilidad Garantizada",
        ingotBenefitsDescription6: "Nuestras prácticas de producción ecológicas y el reciclaje de materiales garantizan que nuestros lingotes contribuyan a un entorno más sostenible, alineándose con las crecientes demandas de la industria",
        ingotBenefitsDescription7: "Flexibilidad y Adaptabilidad",
        ingotBenefitsDescription8: "La variedad en tamaños y formatos de nuestros lingotes permite una fácil adaptación a diferentes procesos y aplicaciones, mejorando la flexibilidad en la producción y satisfaciendo las necesidades específicas de nuestros clientes",

        /* Bars - Product */
        barTitle: "Barras de Aluminio: Fuerza y Precisión en Cada Proyecto",
        barDescription: "Las barras de aluminio de EQUIALUM representan la combinación perfecta de resistencia, ligereza y versatilidad, haciendo de ellas un material esencial en una amplia gama de industrias. Nuestras barras están fabricadas con aluminio de la más alta calidad, garantizando un rendimiento superior en aplicaciones estructurales, mecánicas y decorativas. Diseñadas para cumplir con estrictos estándares industriales, nuestras barras ofrecen una solución confiable para proyectos que demandan precisión y durabilidad",
        barFeauresTitle: "Características Destacadas",
        barFeauresDescription1: "Resistencia Superior",
        barFeauresDescription2: "Nuestras barras de aluminio están diseñadas para soportar altas cargas y tensiones, ofreciendo una excelente resistencia mecánica sin comprometer su ligereza, lo que las hace ideales para aplicaciones estructurales y de ingeniería",
        barFeauresDescription3: "Variedad de Dimensiones y Aleaciones",
        barFeauresDescription4: "Disponemos de una amplia gama de tamaños, diámetros y aleaciones de aluminio, permitiendo a nuestros clientes seleccionar la barra que mejor se ajuste a sus necesidades específicas, ya sea para fabricación, construcción o proyectos especiales",
        barFeauresDescription5: "Excelente Maquinabilidad",
        barFeauresDescription6: "Las barras de aluminio de EQUIALUM son fáciles de cortar, moldear y soldar, ofreciendo una excelente maquinabilidad que facilita su uso en procesos de manufactura complejos y personalizados",
        barFeauresDescription7: "Resistencia a la Corrosión",
        barFeauresDescription8: "Gracias a la naturaleza del aluminio y a los tratamientos aplicados, nuestras barras ofrecen una alta resistencia a la corrosión, incluso en entornos adversos, prolongando la vida útil del producto",
        barBenefitsTitle: "Beneficios",
        barBenefitsDescription1: "Optimización de Procesos Productivos",
        barBenefitsDescription2: "La calidad y versatilidad de nuestras barras de aluminio permiten a las empresas reducir tiempos de producción y mejorar la eficiencia en sus procesos de fabricación, ahorrando costos y recursos",
        barBenefitsDescription3: "Aplicaciones Multisectoriales",
        barBenefitsDescription4: "Desde la industria automotriz y aeroespacial hasta la construcción y electrónica, nuestras barras de aluminio son una solución confiable y eficaz para una amplia gama de aplicaciones industriales",
        barBenefitsDescription5: "Contribución a Proyectos Sostenibles",
        barBenefitsDescription6: "Nuestras barras de aluminio no solo son reciclables al 100%, sino que su ligereza también contribuye a la reducción del consumo de energía y recursos durante su transporte y manejo, promoviendo la sostenibilidad en cada proyecto",
        barBenefitsDescription7: "Acabados de Alta Calidad",
        barBenefitsDescription8: "Ya sea en su estado natural o con acabados personalizados, nuestras barras de aluminio proporcionan un aspecto estético de alta calidad, adecuado tanto para aplicaciones funcionales como decorativas",

        /* Cones - Product */
        coneTitle: "Precisión y Eficiencia en Formas Especializadas",
        coneDescription: "Los conos de aluminio de EQUIALUM están diseñados para satisfacer las necesidades de aplicaciones industriales que requieren formas especializadas con alta precisión y rendimiento. Fabricados con aluminio de calidad superior, nuestros conos ofrecen una solución versátil y duradera para una amplia gama de sectores, desde la industria automotriz hasta la aeroespacial y más allá. Con un enfoque en la precisión dimensional y la integridad estructural, nuestros conos de aluminio aseguran un desempeño confiable en cada proyecto",
        coneFeauresTitle: "Características Destacadas",
        coneFeauresDescription1: "Precisión Dimensional",
        coneFeauresDescription2: "Nuestros conos de aluminio son fabricados con un control riguroso de las dimensiones, garantizando un ajuste perfecto y uniforme en aplicaciones donde la precisión es crucial",
        coneFeauresDescription3: "Resistencia Estructural",
        coneFeauresDescription4: "A pesar de su forma cónica, nuestras piezas conservan una alta resistencia estructural, capaces de soportar cargas significativas sin deformarse, lo que las hace ideales para aplicaciones exigentes",
        coneFeauresDescription5: "Adaptabilidad a Múltiples Procesos",
        coneFeauresDescription6: "Los conos de aluminio de EQUIALUM se adaptan fácilmente a procesos de soldadura, ensamblaje y tratamientos superficiales, proporcionando una gran flexibilidad en su uso y personalización según las necesidades del cliente",
        coneFeauresDescription7: "Acabado de Alta Calidad",
        coneFeauresDescription8: "Cada cono de aluminio recibe un tratamiento de superficie que no solo mejora su resistencia a la corrosión, sino que también ofrece un acabado estético atractivo, adecuado para aplicaciones visibles",
        coneBenefitsTitle: "Beneficios",
        coneBenefitsDescription1: "Soluciones Personalizadas",
        coneBenefitsDescription2: "Ofrecemos conos de aluminio en diversas aleaciones y tamaños, permitiendo a nuestros clientes seleccionar el producto exacto que se ajuste a sus requisitos técnicos y de diseño, optimizando sus procesos de producción",
        coneBenefitsDescription3: "Aplicaciones en Diversos Sectores",
        coneBenefitsDescription4: "Los conos de aluminio de EQUIALUM son esenciales en industrias como la automotriz, aeroespacial y de manufactura, donde se necesitan componentes con formas complejas y propiedades materiales superiores",
        coneBenefitsDescription5: "Contribución a la Eficiencia Operativa",
        coneBenefitsDescription6: "Gracias a su ligereza y facilidad de manejo, los conos de aluminio reducen los costos de transporte y montaje, mejorando la eficiencia operativa y reduciendo los tiempos de producción",
        coneBenefitsDescription7: "Sostenibilidad y Reciclabilidad",
        coneBenefitsDescription8: "Como todos nuestros productos de aluminio, los conos son 100% reciclables, apoyando las iniciativas de sostenibilidad y reduciendo la dependencia de materiales vírgenes en la cadena de suministro",

        /* Liquid - Product */
        liquidTitle: "Precisión y Versatilidad para Procesos de Fundición Avanzados",
        liquidDescription: "El aluminio líquido de EQUIALUM es la solución ideal para industrias que demandan precisión y flexibilidad en sus procesos de fundición. Producido bajo estrictos controles de calidad, nuestro aluminio líquido se caracteriza por su pureza excepcional y consistencia, lo que garantiza la fabricación de componentes de alta calidad con propiedades mecánicas superiores. Este producto es esencial para la producción de piezas complejas en sectores como el automotriz, aeroespacial, y manufacturero, donde la exactitud y la eficiencia son cruciales",
        liquidFeauresTitle: "Características Destacadas",
        liquidFeauresDescription1: "Pureza y Consistencia Superior",
        liquidFeauresDescription2: "Nuestro aluminio líquido se funde a partir de materias primas de alta calidad y se somete a procesos de desgasificación y filtración avanzados, asegurando un metal limpio y homogéneo, libre de impurezas",
        liquidFeauresDescription3: "Adaptabilidad en Procesos de Fundición",
        liquidFeauresDescription4: "El aluminio líquido de EQUIALUM es ideal para una amplia variedad de técnicas de fundición, incluyendo fundición a presión, fundición por gravedad y fundición en arena, lo que permite su uso en la fabricación de piezas con geometrías complejas y acabados finos",
        liquidFeauresDescription5: "Control Térmico Preciso",
        liquidFeauresDescription6: "Ofrecemos aluminio líquido con un control térmico riguroso, que mantiene la temperatura óptima para asegurar un llenado completo de los moldes y la minimización de defectos en la pieza final, como porosidades o inclusiones",
        liquidFeauresDescription7: "Entrega Justo a Tiempo",
        liquidFeauresDescription8: "Nuestra logística está diseñada para suministrar aluminio líquido de manera puntual y segura, adaptándonos a los cronogramas de producción de nuestros clientes y garantizando la continuidad en sus procesos industriales",
        liquidBenefitsTitle: "Beneficios",
        liquidBenefitsDescription1: "Optimización de la Calidad del Producto Final",
        liquidBenefitsDescription2: "Gracias a la alta pureza y consistencia de nuestro aluminio líquido, los componentes fabricados presentan mejores propiedades mecánicas, mayor resistencia y un acabado superior, lo que reduce la necesidad de retrabajos y mejora la eficiencia en la producción",
        liquidBenefitsDescription3: "Reducción de Costos de Producción",
        liquidBenefitsDescription4: "Al ofrecer aluminio líquido de alta calidad, EQUIALUM ayuda a minimizar los defectos en el proceso de fundición, reduciendo los costos asociados con desperdicios, rechazos y reprocesos, y optimizando la rentabilidad de los proyectos",
        liquidBenefitsDescription5: "Versatilidad en Aplicaciones Industriales",
        liquidBenefitsDescription6: "Nuestro aluminio líquido es apto para una variedad de sectores industriales, desde la automoción hasta la fabricación de maquinaria y componentes electrónicos, gracias a su capacidad para adaptarse a diferentes procesos y requisitos de producción",
        liquidBenefitsDescription7: "Contribución a la Eficiencia Energética",
        liquidBenefitsDescription8: "El uso de aluminio líquido reduce los tiempos de ciclo en los procesos de fundición y optimiza el consumo de energía, lo que contribuye a una producción más sostenible y a la reducción de la huella de carbono",

        /* Scrap - Product */
        scrapTitle: "Scrap: Eficiencia y Sostenibilidad para la Industria",
        scrapDescription: "El Scrap de aluminio es un recurso esencial para las industrias que buscan optimizar sus procesos y contribuir a la economía circular. En EQUIALUM, nos especializamos en ofrecer Scrap de aluminio de alta calidad, derivado de fuentes controladas y procesos industriales rigurosos. Este material reciclado no solo reduce los costos de producción, sino que también disminuye significativamente el impacto ambiental, ya que requiere menos energía para su procesamiento en comparación con el aluminio virgen",
        scrapFeauresTitle: "Características Destacadas",
        scrapFeauresDescription1: "Pureza Consistente y Controlada",
        scrapFeauresDescription2: "Nuestro Scrap de aluminio pasa por un proceso de selección y clasificación exhaustivo, garantizando un material con una pureza elevada y homogénea, ideal para su reutilización en diversas aplicaciones industriales",
        scrapFeauresDescription3: "Variedad en Tipos y Formatos",
        scrapFeauresDescription4: "Ofrecemos Scrap en diversas presentaciones, incluyendo láminas, recortes, virutas y más, para adaptarse a las necesidades específicas de cada cliente y proceso industrial",
        scrapFeauresDescription5: "Compromiso con la Sostenibilidad",
        scrapFeauresDescription6: "El Scrap de aluminio de EQUIALUM contribuye a la reducción de la huella de carbono, ya que el reciclaje de aluminio consume solo el 5% de la energía requerida para producir aluminio primario",
        scrapFeauresDescription7: "Eficiencia en la Cadena de Suministro",
        scrapFeauresDescription8: "Gracias a nuestra experiencia y redes logísticas, aseguramos un suministro confiable y puntual de Scrap de aluminio, manteniendo la continuidad en los procesos de producción de nuestros clientes",
        scrapBenefitsTitle: "Beneficios",
        scrapBenefitsDescription1: "Reducción de Costos Operativos",
        scrapBenefitsDescription2: "El uso de Scrap de aluminio permite a las empresas disminuir significativamente los costos de materias primas, optimizando la eficiencia financiera de sus operaciones",
        scrapBenefitsDescription3: "Versatilidad en Aplicaciones Industriales",
        scrapBenefitsDescription4: "El Scrap de aluminio es extremadamente versátil, adecuado para una amplia gama de industrias, desde la automotriz hasta la electrónica y la construcción, sin comprometer las propiedades del aluminio original",
        scrapBenefitsDescription5: "Contribución a la Economía Circular",
        scrapBenefitsDescription6: "Al optar por Scrap de aluminio, las empresas participan activamente en la economía circular, promoviendo prácticas sostenibles y responsables con el medio ambiente",
        scrapBenefitsDescription7: "Alta Calidad del Producto Final",
        scrapBenefitsDescription8: "Pese a ser reciclado, el Scrap de aluminio mantiene las propiedades fundamentales del aluminio, como su resistencia, ligereza y conductividad, asegurando la calidad en los productos finales",

        /* Innovation - Product */
        innovationTitle: "Innovación que Impulsa el Futuro",
        innovationDescription1: "En EQUIALUM, la innovación es el motor que impulsa nuestro crecimiento y mejora continua. Nos enorgullece estar a la vanguardia de la industria del aluminio, invirtiendo en tecnologías avanzadas y procesos que nos permiten ofrecer productos de alta calidad y soluciones personalizadas a nuestros clientes",
        innovationDescription2: "Hemos incorporado máquinas y equipos de última generación, adquiridos de las principales industrias tecnológicas a nivel mundial. Estos equipos nos permiten optimizar nuestros procesos de fundición, mejorando la eficiencia, la precisión y la sostenibilidad de nuestras operaciones. Gracias a esta inversión en tecnología, podemos ofrecer productos que cumplen con los más altos estándares internacionales",
        innovationDescription3: "La innovación en EQUIALUM no se limita solo a la tecnología; también abarca nuestras prácticas operativas y la forma en que nos relacionamos con nuestros clientes. Nos enfocamos en mejorar constantemente nuestros procesos, adoptando nuevas metodologías y enfoques que nos permiten ser más ágiles y responder rápidamente a las necesidades cambiantes del mercado",
        innovation1: "Tecnología de Última Generación",
        innovation2: "Mejora Continua en Procesos",
        innovation3: "Compromiso con la Excelencia",

        /* Appointment */
        appointments: "Contacto",
        appointmentDescription1: "Solicita una Cita con Nuestros Expertos",
        appointmentDescription2: "Solicita una cita con EQUIALUM para recibir asesoramiento personalizado y descubrir cómo nuestros productos de aluminio pueden satisfacer tus necesidades específicas",
        yourName: "Tu nombre",
        yourEmail: "Tu correo electrónico",
        yourPhone: "Tu celular",
        typeOfService: "Tipo de servicio",
        messages: "Mensaje",
        takeAppointment: "Contactar",

        /* Team */
        teamTitle: "Centros de Producción de Excelencia",
        teamDescription: "EQUIALUM cuenta con modernas plantas en Guadalajara y Aguascalientes, equipadas con tecnología de punta para garantizar una producción de aluminio eficiente y de alta calidad. Estas instalaciones están estratégicamente ubicadas, lo que facilita una logística ágil y permite responder rápidamente a las demandas de nuestros clientes, todo mientras mantenemos un firme compromiso con la sostenibilidad y la innovación",
        guadalajara: "Guadalajara",
        plant1: "Planta l",
        aguascalientes: "Aguascalientes",
        plant2: "Planta ll",
        comingSoon: "Muy pronto",
        plant3: "Planta lll",

        /* Testimonial */
        testimonialTitle: "Excelencia en Cada Detalle",
        testimonialDescription1: "Descubre cómo nuestros clientes han experimentado la calidad y el servicio excepcionales de EQUIALUM. Sus testimonios destacan nuestro compromiso con la excelencia y la satisfacción total",
        more100: "100+",
        happyCustomers: "Clientes felices",
        fulfilledProjects: "Proyectos realizados", 
        none: "",
        nameOfCustomer1: "Nombre del Cliente",
        profession1: "Profesión",
        none: "",
        nameOfCustomer2: "Nombre del Cliente",
        profession2: "Profesión",

        /* Footer */
        footerDescription: "EQUIALUM es una empresa líder en la venta de productos de aluminio, ofreciendo lingotes, barras, conos, líquido y scrap",
        footerDescription1: "Contactanos para obtener productos de aluminio de la más alta calidad",
        address: "Dirección",
        streetGdl: "123 Calle, Guadalajara, MX",
        numerPhone: "+52 33 1144 4819",
        emailCompany: "alejandro.garcia@equialum.mx",
        quickLinks: "Enlaces Rápidos",
        termsAndConditions: "Términos y Condiciones",
        politicAndPrivate: "Política de privacidad",
        contactanos: "Contactanos",
        contacto: "Contacto",
        call: "Llamanos: +52 33 1144 4819",
        usEmail: "Email: alejandro.garcia@equialum.mx",
        contactTitle: "Conéctate con EQUIALUM y recibe asistencia personalizada",
        contactSubTitle: "¡Estamos Aquí para Ayudarte!",
        contactDetails: "Detalles de contacto",
        contactData1: "Tecnología avanzada y alta capacidad para producción de aluminio de calidad",
        contactData2: "Innovación y eficiencia en la producción de aluminio, optimizando procesos y calidad",
        contactDescription: "En EQUIALUM, estamos aquí para atender tus necesidades y consultas. Para cualquier pregunta sobre nuestros productos, servicios o información general, no dudes en ponerte en contacto con nosotros. Puedes llamarnos, enviarnos un correo electrónico, o completar nuestro formulario en línea y uno de nuestros representantes se pondrá en contacto contigo a la brevedad. También estamos disponibles a través de nuestras redes sociales para mantenerte informado sobre nuestras últimas noticias y actualizaciones. Tu satisfacción es nuestra prioridad, y estamos comprometidos a brindarte el mejor servicio posible",

    },

    en: {
        /* Topbar */
        daysAndHours: "Monday - Friday: 09 AM - 06 PM",

        /* Navbar */
        home: "Home",
        aboutUs: "About Us",
        ourProducts: "Products",
        pages: "Pages",
        features: "Features",
        appointment: "Appointment",
        ourTeam: "Our Team",
        testimonial: "Testimonial",
        idioms: "Idioms",
        contact: "Contact",

        /* Carousel  */
        welcomeToEQUIALUM: "Welcome to EQUIALUM",
        leadersInAluminumFoundry: "Leaders in Aluminum Foundry",
        innovationAndQualityInEveryForm: "Innovation and Quality in Every Form",
        commercial: "Commercial",
        industrial: "Industrial",
        moreDetails: "More Details",

        years: "Years",
        experience: "Experience",

        /* About */
        talkAboutUs: "Talk About Us",
        innovationAndQualityWithinYourReach: "Innovation And Quality Within Your Reach",
        about1: "We are a Mexican company that stands out for its high quality in comprehensive metal foundry and marketing services",
        about2: "We continually improve our quality management system, we respect the environment, complying with the legal framework and we continually implement process improvements anticipating the needs of our collaborators, suppliers and customers, which makes us a progressive and constantly growing company",
        punctualityInServices: "Punctuality in services",
        excellentService: "Excellent service",
        verifiedProfessionals: "Verified professionals",
        equialumPhilosophy: "EQUIALUM Philosophy",
        equialumCertificate: "EQUIALUM S.A. Certificate of C.V.",

        /* Facts */
        industry: "Industry",
        readMore: "READ MORE",
        automotive: "Automotive",
        fact1: "EQUIALUM supplies high quality products, improving the efficiency and sustainability of vehicles",
        aerospace: "Aerospace",
        fact2: "We provide high quality products that optimize aircraft performance and safety",
        electronics: "Electronics",
        fact3: "We offer high quality products that facilitate the manufacture of reliable and efficient electronic components",
        construction: "Construction",
        fact4: "We supply aluminum products that improve the durability and aesthetics of structures and finishes",

        /* Automotive Industry - Facts */
        automotiveIndustrySubTitle: "Quality Aluminum for High Performance Vehicles",
        automotiveIndustryTitle: "Automotive",
        automotiveIndustryDescription: "EQUIALUM is proud to be a reliable supplier to the automotive industry, offering high quality aluminum that contributes to the manufacture of more efficient and safer vehicles",
        automotiveIndustryDescription1: "Weight Reduction",
        automotiveIndustryDescription2: "EQUIALUM aluminum allows the manufacture of lighter components, reducing the overall weight of the vehicle and improving fuel efficiency",
        automotiveIndustryDescription3: "Durability",
        automotiveIndustryDescription4: "Our aluminum offers high corrosion resistance, ensuring the longevity of automotive parts, even in extreme conditions",
        automotiveIndustryDescription5: "Energy Efficiency",
        automotiveIndustryDescription6: "By reducing the weight of vehicles, our aluminum contributes to lower CO2 emissions and greater energy efficiency, aligning with sustainability trends",
        automotiveIndustryDescription7: "Design Flexibility",
        automotiveIndustryDescription8: "The malleability of EQUIALUM aluminum allows automotive designers to innovate with complex, lightweight shapes, improving the aesthetics and functionality of vehicles",
        automotiveIndustryDescription9: "Regulatory Compliance",
        automotiveIndustryDescription10: "Our products meet strict international standards, guaranteeing safety and quality in automotive applications",
        automotiveIndustryDescription11: "Sustainable Production",
        automotiveIndustryDescription12: "EQUIALUM uses sustainable production processes, minimizing environmental impact and promoting a responsible supply chain",
        automotiveIndustrySubDescription: "EQUIALUM aluminum is essential in the construction of vehicles that seek a balance between performance, safety and sustainability",

        /* Aerospace Industry - Facts */
        aerospaceIndustrySubTitle: "Advanced Materials for Modern Aviation",
        aerospaceIndustryTitle: "Aerospace",
        aerospaceIndustryDescription: "EQUIALUM is a key partner in the aerospace industry, providing high quality aluminum that is essential for the manufacturing of advanced aircraft and aerospace components",
        aerospaceIndustryDescription1: "Performance Optimization",
        aerospaceIndustryDescription2: "Our aluminum helps optimize aircraft performance by reducing weight and improving aerodynamics",
        aerospaceIndustryDescription3: "Extreme Durability",
        aerospaceIndustryDescription4: "EQUIALUM aluminum products are designed to withstand the extreme conditions of the aerospace environment, from high altitudes to extreme temperatures",
        aerospaceIndustryDescription5: "Ease of Maintenance",
        aerospaceIndustryDescription6: "High-quality aluminum reduces maintenance costs by being strong and easy to work with, extending the life of aircraft",
        aerospaceIndustryDescription7: "Guaranteed Security",
        aerospaceIndustryDescription8: "The components manufactured with our aluminum offer greater safety in flights, complying with strict aerospace safety protocols",
        aerospaceIndustryDescription9: "Innovation in Design",
        aerospaceIndustryDescription10: "EQUIALUM facilitates innovation in the aerospace industry, allowing the development of more advanced and efficient aerodynamic designs",
        aerospaceIndustryDescription11: "Reliability in the Supply Chain",
        aerospaceIndustryDescription12: "With a constant and reliable supply, EQUIALUM supports continuous and uninterrupted production in the aerospace industry",
        aerospaceIndustrySubDescription: "EQUIALUM aluminum is essential in creating safer, lighter and more efficient aircraft, supporting technological advances in the aerospace industry",

        /* Electronics Industry - Facts */
        electronicsIndustrySubTitle: "Precision Aluminum for Innovation in the Electronics Industry",
        electronicsIndustryTitle: "Electronics",
        electronicsIndustryDescription: "EQUIALUM offers high quality aluminum that is essential for the development and production of advanced electronic devices, providing precision and reliability",
        electronicsIndustryDescription1: "Heat Dissipation",
        electronicsIndustryDescription2: "Our aluminum is ideal for electronic components, as it facilitates efficient heat dissipation, prolonging the life of the devices",
        electronicsIndustryDescription3: "Lightness and Resistance",
        electronicsIndustryDescription4: "EQUIALUM aluminum provides a robust and lightweight structure for cases and components, without adding unnecessary weight to electronic devices",
        electronicsIndustryDescription5: "Malleability for Design",
        electronicsIndustryDescription6: "Thanks to its malleability, our aluminum allows the manufacture of complex and precise designs, adapting to the needs of modern technology",
        electronicsIndustryDescription7: "Electrical Conductivity",
        electronicsIndustryDescription8: "The aluminum we offer ensures excellent electrical conductivity, ideal for circuits and other critical components in electronics",
        electronicsIndustryDescription9: "Microelectronics Compatibility",
        electronicsIndustryDescription10: "EQUIALUM supplies aluminum compatible with miniaturization, key for the manufacture of compact and efficient electronic devices",
        electronicsIndustryDescription11: "Consistent Quality",
        electronicsIndustryDescription12: "Our aluminum meets the highest industry standards, ensuring quality and reliability in every electronic product",
        electronicsIndustrySubDescription: "EQUIALUM aluminum drives innovation in the electronics industry, providing materials that improve the efficiency and performance of devices",

        /* Construction Industry - Facts */
        constructionIndustrySubTitle: "Cutting-edge Aluminum for Construction Projects",
        constructionIndustryTitle: "Construction",
        constructionIndustryDescription: "EQUIALUM is positioned as a key ally in the construction industry, offering aluminum that provides durability, efficiency and style in modern architectural projects",
        constructionIndustryDescription1: "Superior Durability",
        constructionIndustryDescription2: "Our aluminum is resistant to corrosion and wear, ensuring long-lasting, low-maintenance structures in construction",
        constructionIndustryDescription3: "Lightness and Resistance",
        constructionIndustryDescription4: "EQUIALUM aluminum combines lightness with high resistance, allowing the construction of safer and more sustainable buildings",
        constructionIndustryDescription5: "Design Versatility",
        constructionIndustryDescription6: "With our aluminum, architects and engineers can create innovative and aesthetically appealing designs, without compromising functionality or safety",
        constructionIndustryDescription7: "Energy Efficiency",
        constructionIndustryDescription8: "Our aluminum contributes to energy efficiency in buildings, improving thermal insulation and reducing energy consumption",
        constructionIndustryDescription9: "Ease of Installation",
        constructionIndustryDescription10: "Our aluminum products are easy to work with and install, which speeds up construction times and reduces costs",
        constructionIndustryDescription11: "Regulatory Compliance",
        constructionIndustryDescription12: "EQUIALUM ensures that its aluminum meets the quality and safety standards required by the construction industry",
        constructionIndustrySubDescription: "EQUIALUM aluminum is essential for innovative construction projects, offering solutions that combine resistance, efficiency and sustainability",

        /* Features */
        becauseOur: "Why choose us?",
        features1: "Excellence in Aluminum for Every Industry",
        featuresDescription: "At EQUIALUM, we stand out for offering aluminum products of the highest quality, backed by a commitment to innovation and excellence. Our experience and attention to detail ensure customized solutions that meet the most demanding industry standards, guaranteeing exceptional results on every project",
        bigQuality: "Great quality of products",
        features2: "High purity and resistance aluminum products, manufactured with the strictest quality control standards",
        moreThan12Years: "More than 20 years of professional experience",
        features3: "Adoption of advanced technologies and innovative processes to optimize production and offer tailored solutions",
        continuousInnovation: "Continuous Innovation",
        features4: "Exceptional customer service and adaptability to meet the specific needs of each industry",
        environmentalCommitment: "Environmental Commitment",
        features5: "Sustainable practices and aluminum recycling that contribute to reducing the environmental impact in all processes",

        /* Products */
        productsTitle: "High Quality Aluminum Solutions",
        saw: "Ingots/SAW",
        productsDescription1: "Our aluminum ingots stand out for their high purity and consistent quality, perfect for a variety of industrial applications",
        bars: "Bars",
        productsDescription2: "Our aluminum bars offer durability and versatility, suitable for multiple industrial applications",
        cones: "Cones",
        productsDescription3: "Our aluminum cones are robust and precise, ideal for applications requiring strength and accuracy",
        liquid: "Liquid",
        productsDescription4: "Our liquid aluminum is delivered with high purity and consistency, ideal for casting and molding processes",
        scrap: "Scrap",
        productsDescription5: "Our aluminum scrap is efficient and ecological, ideal for recycling and reuse",
        innovation: "Innovation",
        productsDescription6: "We employ cutting-edge equipment and machines to ensure precise and efficient production processes",

        /* Manufacturing - Products*/
        manufacturingSubTitle: "Manufacturing",
        manufacturingTitle: "Production process",
        manufacturingDescription: "We have a meticulous production process, where we combine advanced technology and experience to create high-quality aluminum products. From raw materials to the final product, each stage is designed to guarantee precision and excellence", 
        manufacturingDescription1: "Every phase of our process, from casting to finishing, is overseen by experts to ensure our products meet the highest industry standards. Our focus on efficiency and quality allows us to offer solutions that exceed our customers' expectations", 

        /* Ingots/SAW - Product */
        ingotTitle: "Purity and Precision for Industrial Applications",
        ingotDescription: "EQUIALUM Aluminum Ingot/SAW is a high quality product designed to meet the exacting demands of various industrial applications. Manufactured from first-melt aluminum, our ingots are characterized by exceptional purity and consistency, ensuring superior performance in any manufacturing process",
        ingotFeauresTitle: "Featured Features",
        ingotFeauresDescription1: "High Purity and Constant Quality",
        ingotFeauresDescription2: "Our aluminum ingots are manufactured with high purity content, ensuring exceptional performance and reliability in industrial applications. This level of purity ensures that each bar meets the highest quality standards",
        ingotFeauresDescription3: "Diversity of Sizes and Formats",
        ingotFeauresDescription4: "We offer ingots in a variety of sizes and standardized formats to suit various industrial processes. This flexibility allows for more efficient integration into different applications, optimizing production",
        ingotFeauresDescription5: "Rigorous Quality Control",
        ingotFeauresDescription6: "Each ingot undergoes strict quality controls, including chemical and physical tests, to ensure that it meets international specifications. This guarantees a reliable and high-performance product",
        ingotFeauresDescription7: "Sustainability and Efficiency",
        ingotFeauresDescription8: "We implement sustainable practices and efficient recycling in the production of our ingots, minimizing the environmental impact and improving the profitability of our clients through optimized processes",
        ingotBenefitsTitle: "Benefits",
        ingotBenefitsDescription1: "Optimal Performance",
        ingotBenefitsDescription2: "The high purity and consistency of our ingots ensure superior performance in casting and manufacturing processes, reducing defects and improving the durability of the final products",
        ingotBenefitsDescription3: "Process Efficiency",
        ingotBenefitsDescription4: "The format and quality of our ingots allow for more efficient and economical processing, optimizing production times and reducing operating costs",
        ingotBenefitsDescription5: "Guaranteed Sustainability",
        ingotBenefitsDescription6: "Our green production practices and material recycling ensure our bullion contributes to a more sustainable environment, aligning with growing industry demands",
        ingotBenefitsDescription7: "Flexibility and Adaptability",
        ingotBenefitsDescription8: "The variety in sizes and formats of our ingots allows easy adaptation to different processes and applications, improving flexibility in production and satisfying the specific needs of our clients",

        /* Bars - Product */
        barTitle: "Aluminum Bars: Strength and Precision in Every Project",
        barDescription: "EQUIALUM aluminum bars represent the perfect combination of strength, lightness and versatility, making them an essential material in a wide range of industries. Our bars are manufactured with the highest quality aluminum, guaranteeing superior performance in structural, mechanical and decorative applications. Engineered to meet strict industry standards, our bars offer a reliable solution for projects that demand precision and durability",
        barFeauresTitle: "Featured Features",
        barFeauresDescription1: "Superior Strength",
        barFeauresDescription2: "Our aluminum bars are designed to withstand high loads and stresses, offering excellent mechanical strength without compromising their lightness, making them ideal for structural and engineering applications",
        barFeauresDescription3: "Variety of Dimensions and Alloys",
        barFeauresDescription4: "We have a wide range of sizes, diameters and aluminum alloys, allowing our customers to select the bar that best suits their specific needs, whether for manufacturing, construction or special projects",
        barFeauresDescription5: "Excellent Machinability",
        barFeauresDescription6: "EQUIALUM aluminum bars are easy to cut, shape and weld, offering excellent machinability that facilitates their use in complex and customized manufacturing processes",
        barFeauresDescription7: "Corrosion Resistance",
        barFeauresDescription8: "Thanks to the nature of aluminum and the treatments applied, our bars offer high resistance to corrosion, even in adverse environments, prolonging the useful life of the product",
        barBenefitsTitle: "Benefits",
        barBenefitsDescription1: "Optimization of Productive Processes",
        barBenefitsDescription2: "The quality and versatility of our aluminum bars allow companies to reduce production times and improve efficiency in their manufacturing processes, saving costs and resources",
        barBenefitsDescription3: "Multisector Applications",
        barBenefitsDescription4: "From automotive and aerospace to construction and electronics, our aluminum bars are a reliable and effective solution for a wide range of industrial applications",
        barBenefitsDescription5: "Contribution to Sustainable Projects",
        barBenefitsDescription6: "Our aluminum bars are not only 100% recyclable, but their lightness also contributes to the reduction of energy and resource consumption during transportation and handling, promoting sustainability in each project",
        barBenefitsDescription7: "High Quality Finishes",
        barBenefitsDescription8: "Whether in their natural state or with custom finishes, our aluminum bars provide a high-quality aesthetic appearance, suitable for both functional and decorative applications",

        /* Cones - Product */
        coneTitle: "Precision and Efficiency in Specialized Shapes",
        coneDescription: "EQUIALUM aluminum cones are designed to meet the needs of industrial applications that require specialized shapes with high precision and performance. Manufactured from premium aluminum, our cones offer a versatile, durable solution for a wide range of sectors, from automotive to aerospace and beyond. With a focus on dimensional accuracy and structural integrity, our aluminum cones ensure reliable performance on every project",
        coneFeauresTitle: "Featured Features",
        coneFeauresDescription1: "Dimensional Accuracy",
        coneFeauresDescription2: "Our aluminum cones are manufactured with rigorous control of dimensions, guaranteeing a perfect and uniform fit in applications where precision is crucial",
        coneFeauresDescription3: "Structural Strength",
        coneFeauresDescription4: "Despite their conical shape, our parts retain high structural strength, capable of supporting significant loads without deforming, making them ideal for demanding applications",
        coneFeauresDescription5: "Adaptability to Multiple Processes",
        coneFeauresDescription6: "EQUIALUM aluminum cones easily adapt to welding, assembly and surface treatment processes, providing great flexibility in their use and customization according to customer needs",
        coneFeauresDescription7: "High Quality Finish",
        coneFeauresDescription8: "Each aluminum cone receives a surface treatment that not only improves its corrosion resistance but also offers an attractive aesthetic finish, suitable for visible applications",
        coneBenefitsTitle: "Benefits",
        coneBenefitsDescription1: "Custom Solutions",
        coneBenefitsDescription2: "We offer aluminum cones in various alloys and sizes, allowing our customers to select the exact product that fits their technical and design requirements, optimizing their production processes",
        coneBenefitsDescription3: "Applications in Various Sectors",
        coneBenefitsDescription4: "EQUIALUM aluminum cones are essential in industries such as automotive, aerospace and manufacturing, where components with complex shapes and superior material properties are needed",
        coneBenefitsDescription5: "Contribution to Operational Efficiency",
        coneBenefitsDescription6: "Thanks to their lightness and ease of handling, aluminum cones reduce transportation and assembly costs, improving operational efficiency and reducing production times",
        coneBenefitsDescription7: "Sustainability and Recyclability",
        coneBenefitsDescription8: "Like all our aluminum products, the cones are 100% recyclable, supporting sustainability initiatives and reducing reliance on virgin materials in the supply chain",

        /* Liquid - Product */
        liquidTitle: "Precision and Versatility for Advanced Casting Processes",
        liquidDescription: "EQUIALUM liquid aluminum is the ideal solution for industries that demand precision and flexibility in their casting processes. Produced under strict quality controls, our liquid aluminum is characterized by its exceptional purity and consistency, ensuring the manufacture of high-quality components with superior mechanical properties. This product is essential for the production of complex parts in sectors such as automotive, aerospace, and manufacturing, where accuracy and efficiency are crucial",
        liquidFeauresTitle: "Featured Features",
        liquidFeauresDescription1: "Superior Purity and Consistency",
        liquidFeauresDescription2: "Our liquid aluminum is cast from high-quality raw materials and undergoes advanced degassing and filtration processes, ensuring a clean, homogeneous metal, free of impurities",
        liquidFeauresDescription3: "Adaptability in Foundry Processes",
        liquidFeauresDescription4: "EQUIALUM liquid aluminum is ideal for a wide variety of casting techniques, including die casting, gravity casting and sand casting, allowing it to be used in the manufacture of parts with complex geometries and fine finishes",
        liquidFeauresDescription5: "Precise Thermal Control",
        liquidFeauresDescription6: "We offer liquid aluminum with rigorous thermal control, which maintains the optimal temperature to ensure complete filling of the molds and the minimization of defects in the final part, such as porosities or inclusions",
        liquidFeauresDescription7: "Just in Time Delivery",
        liquidFeauresDescription8: "Our logistics is designed to supply liquid aluminum in a timely and safe manner, adapting to our clients' production schedules and guaranteeing continuity in their industrial processes",
        liquidBenefitsTitle: "Benefits",
        liquidBenefitsDescription1: "Optimization of Final Product Quality",
        liquidBenefitsDescription2: "Thanks to the high purity and consistency of our liquid aluminum, manufactured components have better mechanical properties, greater strength and a superior finish, reducing the need for rework and improving production efficiency",
        liquidBenefitsDescription3: "Production Cost Reduction",
        liquidBenefitsDescription4: "By offering high-quality liquid aluminum, EQUIALUM helps minimize defects in the casting process, reducing costs associated with scrap, rejects and rework, and optimizing project profitability",
        liquidBenefitsDescription5: "Versatility in Industrial Applications",
        liquidBenefitsDescription6: "Our liquid aluminum is suitable for a variety of industrial sectors, from automotive to machinery and electronic component manufacturing, thanks to its ability to adapt to different production processes and requirements",
        liquidBenefitsDescription7: "Contribution to Energy Efficiency",
        liquidBenefitsDescription8: "The use of liquid aluminum reduces cycle times in casting processes and optimizes energy consumption, contributing to more sustainable production and reducing the carbon footprint",

        /* Scrap - Product */
        scrapTitle: "Scrap: Efficiency and Sustainability for the Industry",
        scrapDescription: "Aluminum Scrap is an essential resource for industries seeking to optimize their processes and contribute to the circular economy. At EQUIALUM, we specialize in offering high quality Aluminum Scrap, derived from controlled sources and rigorous industrial processes. This recycled material not only reduces production costs, but also significantly reduces environmental impact, as it requires less energy to process compared to virgin aluminum",
        scrapFeauresTitle: "Featured Features",
        scrapFeauresDescription1: "Consistent and Controlled Purity",
        scrapFeauresDescription2: "Our Aluminum Scrap goes through an exhaustive selection and classification process, guaranteeing a material with high and homogeneous purity, ideal for reuse in various industrial applications",
        scrapFeauresDescription3: "Variety in Types and Formats",
        scrapFeauresDescription4: "We offer Scrap in various presentations, including sheets, cuts, shavings and more, to adapt to the specific needs of each client and industrial process",
        scrapFeauresDescription5: "Commitment to Sustainability",
        scrapFeauresDescription6: "EQUIALUM Aluminum Scrap contributes to the reduction of the carbon footprint, since aluminum recycling consumes only 5% of the energy required to produce primary aluminum",
        scrapFeauresDescription7: "Supply Chain Efficiency",
        scrapFeauresDescription8: "Thanks to our experience and logistics networks, we ensure a reliable and punctual supply of Aluminum Scrap, maintaining continuity in our clients' production processes",
        scrapBenefitsTitle: "Benefits",
        scrapBenefitsDescription1: "Reduction of Operating Costs",
        scrapBenefitsDescription2: "The use of aluminum scrap allows companies to significantly reduce raw material costs, optimizing the financial efficiency of their operations",
        scrapBenefitsDescription3: "Versatility in Industrial Applications",
        scrapBenefitsDescription4: "Aluminum Scrap is extremely versatile, suitable for a wide range of industries, from automotive to electronics and construction, without compromising the properties of the original aluminum",
        scrapBenefitsDescription5: "Contribution to the Circular Economy",
        scrapBenefitsDescription6: "By choosing aluminum scrap, companies actively participate in the circular economy, promoting sustainable and environmentally responsible practices",
        scrapBenefitsDescription7: "High Quality of the Final Product",
        scrapBenefitsDescription8: "Despite being recycled, Aluminum Scrap maintains the fundamental properties of aluminum, such as its resistance, lightness and conductivity, ensuring the quality of the final products",

        /* Innovation - Product */
        innovationTitle: "Innovation that Drives the Future",
        innovationDescription1: "At EQUIALUM, innovation is the engine that drives our growth and continuous improvement. We are proud to be at the forefront of the aluminum industry, investing in advanced technologies and processes that allow us to offer high quality products and customized solutions to our customers",
        innovationDescription2: "We have incorporated state-of-the-art machines and equipment, acquired from the main technological industries worldwide. This equipment allows us to optimize our foundry processes, improving the efficiency, precision and sustainability of our operations. Thanks to this investment in technology, we can offer products that meet the highest international standards",
        innovationDescription3: "Innovation at EQUIALUM is not limited only to technology; It also encompasses our operating practices and the way we engage with our customers. We focus on constantly improving our processes, adopting new methodologies and approaches that allow us to be more agile and respond quickly to changing market needs",
        innovation1: "Latest Generation Technology",
        innovation2: "Continuous Improvement in Processes",
        innovation3: "Commitment to Excellence",

        /* Appointment */
        appointments: "Contact",
        appointmentDescription1: "Request an Appointment with Our Experts",
        appointmentDescription2: "Request an appointment with EQUIALUM to receive personalized advice and discover how our aluminum products can meet your specific needs",
        yourName: "Your name",
        yourEmail: "Your e-mail",
        yourPhone: "Your cellphone",
        typeOfService: "Type of service",
        messages: "Message",
        takeAppointment: "Contact",

        /* Team */
        teamTitle: "Production Centers of Excellence",
        teamDescription: "EQUIALUM has modern plants in Guadalajara and Aguascalientes, equipped with cutting-edge technology to guarantee efficient and high-quality aluminum production. These facilities are strategically located, facilitating agile logistics and allowing us to respond quickly to our customers' demands, all while maintaining a firm commitment to sustainability and innovation",
        plant1: "Production Plant l",
        aguascalientes: "Aguascalientes",
        plant2: "Production Plant ll",
        comingSoon: "Coming Soon",
        plant3: "Production Plant lll",

        /* Testimonial */
        testimonialTitle: "Excellence in Every Detail",
        testimonialDescription1: "Discover how our customers have experienced EQUIALUM's exceptional quality and service. Your testimonials highlight our commitment to excellence and total satisfaction",
        more100: "100+",
        happyCustomers: "Happy clients",
        fulfilledProjects: "Fulfilled projects", 
        none: "",
        nameOfCustomer1: "Customer name",
        profession1: "Profession",
        none: "",
        nameOfCustomer2: "Customer name",
        profession2: "Profession",

        /* Footer */
        footerDescription: "EQUIALUM is a leading company in the sale of aluminum products, offering ingots, bars, cones, liquid and scrap",
        footerDescription1: "Contact us for the highest quality aluminum products",
        address: "Address",
        streetGdl: "123 Calle, Guadalajara, MX",
        numerPhone: "+52 33 1144 4819",
        emailCompany: "alejandro.garcia@equialum.mx",
        quickLinks: "Quick Links",
        termsAndConditions: "Terms and Conditions",
        politicAndPrivate: "Privacy Policy",
        contactanos: "Contact us",
        contacto: "Contact",
        call: "Call us: +52 33 1144 4819",
        usEmail: "Email: alejandro.garcia@equialum.mx",
        contactTitle: "Connect with EQUIALUM and receive personalized assistance",
        contactSubTitle: "We are here to help you!",
        contactDetails: "Contact Details",
        contactData1: "Advanced technology and high capacity for quality aluminum production",
        contactData2: "Innovation and efficiency in aluminum production, optimizing processes and quality",
        contactDescription: "At EQUIALUM, we are here to address your needs and queries. For any questions about our products, services or general information, do not hesitate to contact us. You can call us, send us an email, or fill out our online form and one of our representatives will contact you shortly. We are also available through our social networks to keep you informed about our latest news and updates. Your satisfaction is our priority, and we are committed to providing you with the best service possible",
    },

    jp: {
        /* Topbar */
        daysAndHours: "月～金：午前9時～午後6時",

        /* Navbar */
        home: "ホーム",
        aboutUs: "会社概要",
        ourProducts: "当社の製品",
        pages: "ページ",
        features: "特徴",
        appointment: "予約する",
        ourTeam: "チーム紹介",
        testimonial: "証言",
        idioms: "言語",
        contact: "連絡先",

        /* Carousel  */
        welcomeToEQUIALUM: "EQUIALUMへようこそ",
        leadersInAluminumFoundry: "アルミニウム製錬のリーダー",
        innovationAndQualityInEveryForm: "あらゆる形における革新と品質",
        commercial: "コマーシャル",
        industrial: "インダストリアル",
        moreDetails: "詳細",

        years: "年",
        experience: "経験",

        /* About */
        talkAboutUs: "会社概要",
        innovationAndQualityWithinYourReach: "革新と品質を手の届くところに",
        about1: "当社は、包括的な鋳造サービスと金属製品化における高い品質で際立つメキシコの企業です。",
        about2: "品質管理システムを継続的に改善し、環境を尊重し、法的枠組みを遵守し、従業員、サプライヤー、顧客のニーズを先取りしてプロセスの改善を継続的に実施することで、当社は進歩的な成長企業となっている。",
        punctualityInServices: "サービスの時間厳守",
        excellentService: "素晴らしいサービス",
        verifiedProfessionals: "検証されたプロフェッショナル",
        equialumPhilosophy: "エクイリアムの理念",
        equialumCertificate: "認証済み EQUIALUM S.A. de C.V.",

        /* Facts */
        industry: "産業",
        readMore: "続きを読む",
        automotive: "自動車",
        fact1: "エクイアルムは、自動車の効率と持続可能性を向上させる高品質の製品を提供しています。",
        aerospace: "航空宇宙",
        fact2: "航空機の性能と安全性を最適化する高品質な製品を提供しています。",
        electronics: "エレクトロニクス",
        fact3: "信頼性が高く効率的な電子部品の製造を促進する高品質な製品を提供しています。",
        construction: "建設",
        fact4: "当社は、構造物や仕上げの耐久性と美観を高めるアルミ製品を提供しています。",

        /* Automotive Industry - Facts */
        automotiveIndustrySubTitle: "高性能車用の高品質アルミニウム",
        automotiveIndustryTitle: "自動車",
        automotiveIndustryDescription: "EQUIALUMは、自動車業界の信頼できるサプライヤーであることを誇りに思い、自動車の効率性と安全性の向上に貢献する高品質のアルミニウムを提供しています。",
        automotiveIndustryDescription1: "軽量化",
        automotiveIndustryDescription2: "EQUIALUMアルミニウムは、より軽量な部品の製造を可能にし、車両全体の重量を減らし、燃費を向上させます。",
        automotiveIndustryDescription3: "耐久性",
        automotiveIndustryDescription4: "当社のアルミニウムは高い耐食性を持ち、過酷な条件下でも自動車部品の寿命を保証します。",
        automotiveIndustryDescription5: "エネルギー効率",
        automotiveIndustryDescription6: "車両の軽量化により、当社のアルミニウムはCO2排出量の削減とエネルギー効率の向上に貢献し、持続可能性のトレンドに沿ったものとなっている。",
        automotiveIndustryDescription7: "デザインの柔軟性",
        automotiveIndustryDescription8: "エクイアルム・アルミニウムの可鍛性により、自動車設計者は複雑で軽量な形状を革新し、自動車の美観と機能性を高めることができます。",
        automotiveIndustryDescription9: "規制遵守",
        automotiveIndustryDescription10: "当社の製品は厳しい国際規格に準拠しており、自動車用途における安全性と品質を保証しています。",
        automotiveIndustryDescription11: "持続可能な生産",
        automotiveIndustryDescription12: "エクイアルムは持続可能な生産工程を採用し、環境への影響を最小限に抑え、責任あるサプライチェーンを推進しています。",
        automotiveIndustrySubDescription: "エクイアルム・アルミニウムは、性能、安全性、持続可能性のバランスを追求する自動車の製造に不可欠です。",

        /* Aerospace Industry - Facts */
        aerospaceIndustrySubTitle: "現代航空機のための先端材料",
        aerospaceIndustryTitle: "航空宇宙",
        aerospaceIndustryDescription: "エクイアルムは航空宇宙産業における重要なパートナーであり、高度な航空機や航空宇宙部品の製造に不可欠な高品質のアルミニウムを提供しています。",
        aerospaceIndustryDescription1: "パフォーマンスの最適化",
        aerospaceIndustryDescription2: "当社のアルミニウムは、軽量化と空気力学の改善によって航空機の性能を最適化するのに役立っています。",
        aerospaceIndustryDescription3: "究極の耐久性",
        aerospaceIndustryDescription4: "エキアルムアルミニウム製品は、高高度から極端な温度まで、航空宇宙環境の極限に耐えるように設計されています。",
        aerospaceIndustryDescription5: "メンテナンスの容易さ",
        aerospaceIndustryDescription6: "高品質のアルミニウムは、強度が高く加工しやすいためメンテナンスコストを削減し、航空機の寿命を延ばす。",
        aerospaceIndustryDescription7: "セキュリティ保証",
        aerospaceIndustryDescription8: "当社のアルミニウムから作られた部品は、厳格な航空宇宙安全プロトコルに準拠し、飛行の安全性を高めます。",
        aerospaceIndustryDescription9: "デザインの革新",
        aerospaceIndustryDescription10: "エクイアルムは、航空宇宙産業における技術革新を促進し、より高度で効率的な空力設計の開発を可能にします。",
        aerospaceIndustryDescription11: "サプライチェーンの信頼性",
        aerospaceIndustryDescription12: "安定した信頼性の高い供給により、EQUIALUMは航空宇宙産業における継続的で中断のない生産をサポートします。",
        aerospaceIndustrySubDescription: "エキアルムアルミニウムは、より安全で、より軽く、より効率的な航空機の製造に役立っており、航空宇宙産業の技術的進歩を支えています。",

        /* Electronics Industry - Facts */
        electronicsIndustrySubTitle: "エレクトロニクス産業における革新のための精密アルミニウム",
        electronicsIndustryTitle: "エレクトロニクス",
        electronicsIndustryDescription: "エクイアルムは、高度な電子機器の開発と生産に不可欠な高品質アルミニウムを提供し、精度と信頼性を提供します。",
        electronicsIndustryDescription1: "放熱",
        electronicsIndustryDescription2: "当社のアルミニウムは、効率的な放熱を促進し、デバイスの寿命を延ばすため、電子部品に最適です。",
        electronicsIndustryDescription3: "軽さと耐性",
        electronicsIndustryDescription4: "EQUIALUMアルミニウムは、電子機器に不必要な重量を加えることなく、筐体や部品に堅牢で軽量な構造を提供します。",
        electronicsIndustryDescription5: "デザインの可鍛性",
        electronicsIndustryDescription6: "その可鍛性のおかげで、当社のアルミニウムは複雑で精密な設計の製造を可能にし、現代技術のニーズに適応します。",
        electronicsIndustryDescription7: "電気伝導度",
        electronicsIndustryDescription8: "当社が提供するアルミは、優れた導電性を確保し、電子機器における回路やその他の重要な部品に理想的です。",
        electronicsIndustryDescription9: "マイクロエレクトロニクスとの互換性",
        electronicsIndustryDescription10: "EQUIALUMは、小型で効率的な電子機器製造の鍵となる小型化に適合するアルミニウムを供給しています。",
        electronicsIndustryDescription11: "一貫した品質",
        electronicsIndustryDescription12: "当社のアルミニウムは業界最高水準を満たしており、すべてのエレクトロニクス製品の品質と信頼性を保証しています。",
        electronicsIndustrySubDescription: "EQUIALUMアルミニウムは、エレクトロニクス業界の技術革新を推進し、デバイスの効率と性能を向上させる材料を提供しています。",

        /* Construction Industry - Facts */
        constructionIndustrySubTitle: "建設プロジェクト向け最先端アルミニウム",
        constructionIndustryTitle: "建設",
        constructionIndustryDescription: "エクイアルムは、建設業界における重要なパートナーとして位置づけられ、現代の建築プロジェクトに耐久性、効率性、スタイルをもたらすアルミニウムを提供しています。",
        constructionIndustryDescription1: "優れた耐久性",
        constructionIndustryDescription2: "当社のアルミニウムは耐食性・耐摩耗性に優れ、耐久性が高く、メンテナンスの手間が少ない建築構造物を実現します。",
        constructionIndustryDescription3: "軽さと耐性",
        constructionIndustryDescription4: "エクイアルム・アルミニウムは、軽さと高い強度を兼ね備えており、より安全で持続可能な建築物の建設を可能にします。",
        constructionIndustryDescription5: "デザインの多様性",
        constructionIndustryDescription6: "当社のアルミニウムを使用することで、建築家やエンジニアは、機能性や安全性を損なうことなく、革新的で審美的に魅力的な設計を行うことができます。",
        constructionIndustryDescription7: "エネルギー効率",
        constructionIndustryDescription8: "当社のアルミニウムは、建物のエネルギー効率に貢献し、断熱性を高め、エネルギー消費を削減します。",
        constructionIndustryDescription9: "インストールの容易さ",
        constructionIndustryDescription10: "当社のアルミ製品は作業や設置が簡単なため、工期を短縮し、コストを削減することができます。",
        constructionIndustryDescription11: "規制遵守",
        constructionIndustryDescription12: "エクイアルムは、そのアルミニウムが建設業界が求める品質と安全基準を満たすことを保証します。",
        constructionIndustrySubDescription: "エクイアルムアルミニウムは、革新的な建設プロジェクトに不可欠であり、強度、効率性、持続可能性を兼ね備えたソリューションを提供します。",

        /* Features */
        becauseOur: "私たちを選ぶ理由",
        features1: "あらゆる産業向けの卓越したアルミニウム",
        featuresDescription: "エクイアルムは、イノベーションと卓越性へのコミットメントに裏打ちされた、最高品質のアルミニウム製品を提供することで知られています。当社の経験と細部へのこだわりが、最も要求の厳しい業界基準を満たすカスタマイズされたソリューションを保証し、すべてのプロジェクトにおいて卓越した結果をお約束します。",
        bigQuality: "高品質の製品",
        features2: "最も厳しい品質管理基準に従って製造された高純度・高強度のアルミニウム製品。",
        moreThan12Years: "20年以上のプロフェッショナルとしての経験",
        features3: "高度な技術と革新的なプロセスを採用し、生産を最適化し、オーダーメイドのソリューションを提供する。",
        continuousInnovation: "継続的イノベーション",
        features4: "卓越した顧客サービスと業界特有のニーズに対応する適応力",
        environmentalCommitment: "環境への取り組み",
        features5: "持続可能な慣行とアルミニウムのリサイクルは、すべてのプロセスにおいて環境負荷の低減に貢献する。",

        /* Products */
        productsTitle: "高品質アルミニウム・ソリューション",
        saw: "地金/SAW",
        productsDescription1: "当社のアルミニウム地金は、高純度で安定した品質を特徴としており、様々な産業用途に最適です。",
        bars: "バー",
        productsDescription2: "当社のアルミバーは、耐久性と汎用性があり、さまざまな産業用途に適しています。",
        cones: "コーンズ",
        productsDescription3: "当社のアルミ製コーンは頑丈で精密であり、強度と精度が要求される用途に最適です。",
        liquid: "液体",
        productsDescription4: "当社の液体アルミニウムは、鋳造や成型工程に理想的な、高純度で一貫性のある状態で供給されます。",
        scrap: "スクラップ",
        productsDescription5: "当社のアルミスクラップは効率的で環境に優しく、リサイクルや再利用に最適です。",
        innovation: "イノベーション",
        productsDescription6: "私たちは、正確で効率的な生産工程を確保するために、最先端の設備と機械を使用しています。",

        /* Manufacturing - Products */
        manufacturingSubTitle: "製造業",
        manufacturingTitle: "生産プロセス",
        manufacturingDescription: "私たちは、高度な技術と専門知識を結集して高品質のアルミニウム製品を生み出す、綿密な製造工程を持っています。原材料から完成品に至るまで、すべての工程は精度と卓越性を保証するために設計されています。", 
        manufacturingDescription1: "鋳造から仕上げまでの各工程では、当社の製品が業界最高水準を満たすよう、専門家による監視が行われています。効率と品質を重視することで、お客様の期待を上回るソリューションを提供することができるのです。", 

        /* Ingots/SAW - Product */
        ingotTitle: "産業用アプリケーションのための純度と精度",
        ingotDescription: "EQUIALUMのアルミニウムインゴット/SAWは、様々な産業用途の厳しい要求を満たすように設計された高品質の製品です。初溶融アルミニウムから製造される当社のインゴットは、卓越した純度と一貫性を特徴としており、どのような製造工程においても優れた性能を保証します。",
        ingotFeauresTitle: "卓越した機能",
        ingotFeauresDescription1: "高純度で安定した品質",
        ingotFeauresDescription2: "当社のアルミニウム地金は高純度で製造されており、工業用途において卓越した性能と信頼性を保証します。この純度レベルは、各インゴットが最高の品質基準を満たすことを保証します。",
        ingotFeauresDescription3: "多様なサイズと形式",
        ingotFeauresDescription4: "当社では、さまざまな工業プロセスに適合するよう、標準化されたさまざまなサイズと形式のインゴットを提供しています。この柔軟性により、さまざまな用途への効率的な統合が可能になり、生産が最適化されます。",
        ingotFeauresDescription5: "厳格な品質管理",
        ingotFeauresDescription6: "各インゴットは、化学的および物理的テストを含む厳格な品質管理を受け、国際仕様に適合していることが保証される。これにより、信頼性の高い高性能製品が保証される。",
        ingotFeauresDescription7: "持続可能性と効率性",
        ingotFeauresDescription8: "インゴットの生産において持続可能な慣行と効率的なリサイクルを実施し、環境への影響を最小限に抑え、最適化されたプロセスを通じて顧客の収益性を向上させる。",
        ingotBenefitsTitle: "メリット",
        ingotBenefitsDescription1: "最適なパフォーマンス",
        ingotBenefitsDescription2: "当社のインゴットの高い純度と一貫性は、鋳造および製造工程における優れた性能を保証し、欠陥を減らし、最終製品の耐久性を向上させます。",
        ingotBenefitsDescription3: "プロセス効率",
        ingotBenefitsDescription4: "当社のインゴットの形式と品質は、より効率的で経済的な加工を可能にし、生産時間の最適化と操業コストの削減を実現する。",
        ingotBenefitsDescription5: "持続可能性の保証",
        ingotBenefitsDescription6: "環境に配慮した製造方法と材料のリサイクルにより、当社のインゴットは、業界の高まる需要に沿い、より持続可能な環境に貢献しています。",
        ingotBenefitsDescription7: "柔軟性と適応性",
        ingotBenefitsDescription8: "当社のインゴットはサイズや形式が多様であるため、さまざまなプロセスや用途に容易に適合させることができ、生産における柔軟性が向上し、顧客の具体的なニーズに応えることができる。",

        /* Bars - Product */
        barTitle: "アルミニウム棒：あらゆるプロジェクトにおける強度と精度",
        barDescription: "EQUIALUMアルミ棒材は、強度、軽さ、汎用性の完璧な組み合わせであり、幅広い産業で不可欠な材料となっています。当社の棒材は、最高品質のアルミニウムから製造されており、構造、機械、装飾の各用途で優れた性能を発揮します。厳しい業界基準を満たすように設計された当社の棒材は、精度と耐久性が求められるプロジェクトに信頼できるソリューションを提供します。",
        barFeauresTitle: "卓越した機能",
        barFeauresDescription1: "優れた耐性",
        barFeauresDescription2: "当社のアルミ棒は、高荷重と応力に耐えるように設計されており、軽量性を損なうことなく優れた機械的強度を提供するため、構造用途やエンジニアリング用途に理想的です。",
        barFeauresDescription3: "多様な寸法と合金",
        barFeauresDescription4: "当社では、幅広いサイズ、直径、アルミ合金を取り揃えており、加工、建設、特殊プロジェクトなど、お客様の特定のニーズに最も適した棒鋼をお選びいただけます。",
        barFeauresDescription5: "優れた加工性",
        barFeauresDescription6: "EQUIALUMアルミ棒材は、切断、成形、溶接が容易で、複雑でカスタマイズされた製造工程で使用できる優れた加工性を提供します。",
        barFeauresDescription7: "耐食性",
        barFeauresDescription8: "アルミニウムの性質と施された処理により、当社の棒材は過酷な環境下でも高い耐食性を発揮し、製品の寿命を延ばします。",
        barBenefitsTitle: "メリット",
        barBenefitsDescription1: "生産プロセスの最適化",
        barBenefitsDescription2: "当社のアルミ棒の品質と汎用性により、企業は製造時間を短縮し、製造工程の効率を向上させ、コストと資源を節約することができます。",
        barBenefitsDescription3: "多方面への応用",
        barBenefitsDescription4: "自動車、航空宇宙から建設、エレクトロニクスに至るまで、当社のアルミニウム棒は、幅広い産業用途に対応する信頼性の高い効果的なソリューションです。",
        barBenefitsDescription5: "持続可能なプロジェクトへの貢献",
        barBenefitsDescription6: "当社のアルミバーは100％リサイクル可能なだけでなく、軽量であるため、輸送や取り扱いの際のエネルギーや資源の消費削減にも貢献し、あらゆるプロジェクトにおいて持続可能性を促進します。",
        barBenefitsDescription7: "高品質仕上げ",
        barBenefitsDescription8: "自然な状態でも、特注仕上げでも、当社のアルミ棒は、機能的用途にも装飾的用途にも適した、高品質の美的外観を提供します。",

        /* Cones - Product */
        coneTitle: "特殊フォームの精度と効率",
        coneDescription: "EQUIALUMのアルミコーンは、高い精度と性能を備えた特殊形状を必要とする産業用途のニーズを満たすように設計されています。優れた品質のアルミニウムから製造される当社の円錐形は、自動車から航空宇宙まで、幅広い分野に汎用性と耐久性のあるソリューションを提供します。寸法精度と構造的完全性に重点を置いた当社のアルミコーンは、あらゆるプロジェクトで信頼できる性能を保証します。",
        coneFeauresTitle: "卓越した機能",
        coneFeauresDescription1: "寸法精度",
        coneFeauresDescription2: "当社のアルミコーンは、厳格な寸法管理で製造されており、精度が重要な用途において、完璧で均一な適合を保証します。",
        coneFeauresDescription3: "構造抵抗",
        coneFeauresDescription4: "円錐形にもかかわらず、当社の部品は高い構造強度を保持しており、変形することなく大きな荷重に耐えることができるため、要求の厳しい用途に最適です。",
        coneFeauresDescription5: "複数のプロセスへの適応性",
        coneFeauresDescription6: "エキアルムアルミニウムコーンは、溶接、組立、表面処理工程に容易に適合するため、使用上の柔軟性が高く、お客様のニーズに応じてカスタマイズすることができます。",
        coneFeauresDescription7: "高品質仕上げ",
        coneFeauresDescription8: "各アルミ製コーンには、耐食性を向上させるだけでなく、目に見える用途に適した魅力的な美的仕上げを施す表面処理が施されています。",
        coneBenefitsTitle: "メリット",
        coneBenefitsDescription1: "カスタマイズ・ソリューション",
        coneBenefitsDescription2: "当社では、様々な合金とサイズのアルミコーンを提供しており、お客様が技術的・設計的要件に合わせて正確な製品を選択し、生産工程を最適化できるようにしています。",
        coneBenefitsDescription3: "様々な分野での応用",
        coneBenefitsDescription4: "エキアルムアルミコーンは、自動車、航空宇宙、製造業など、複雑な形状と優れた材料特性を持つ部品が必要とされる産業で不可欠です。",
        coneBenefitsDescription5: "経営効率への貢献",
        coneBenefitsDescription6: "軽量で取り扱いが容易なため、アルミコーンは輸送と組み立てのコストを削減し、作業効率を高めて生産時間を短縮します。",
        coneBenefitsDescription7: "持続可能性とリサイクル性",
        coneBenefitsDescription8: "当社の他のアルミニウム製品と同様、このコーンも100％リサイクル可能で、持続可能なイニシアチブを支援し、サプライチェーンにおけるバージン材料への依存を減らしている。",

        /* Liquid - Product */
        liquidTitle: "高度な鋳造プロセスのための精度と汎用性",
        liquidDescription: "エキアルムのリキッドアルミニウムは、鋳造工程に精度と柔軟性を求める産業にとって理想的なソリューションです。厳格な品質管理の下で製造される当社の液体アルミニウムは、その卓越した純度と一貫性が特徴で、優れた機械的特性を持つ高品質の部品の製造を保証します。この製品は、自動車、航空宇宙、製造業など、精度と効率が重要な分野における複雑な部品の製造に不可欠です。",
        liquidFeauresTitle: "卓越した機能",
        liquidFeauresDescription1: "優れた純度と一貫性",
        liquidFeauresDescription2: "当社の液体アルミニウムは、高品質の原料から製錬され、高度な脱ガス・ろ過工程を経て、不純物のないクリーンで均質な金属が確保される。",
        liquidFeauresDescription3: "鋳造プロセスにおける適応性",
        liquidFeauresDescription4: "エクイアルムのリキッドアルミニウムは、ダイカスト、重力鋳造、砂型鋳造を含む様々な鋳造技術に最適で、複雑な形状や微細な仕上げを持つ部品の製造に使用することができます。",
        liquidFeauresDescription5: "精密な熱制御",
        liquidFeauresDescription6: "私たちは、金型への完全な充填を保証し、空隙や介在物などの最終部品の欠陥を最小限に抑えるために最適な温度を維持する、厳格な熱制御を備えた液体アルミニウムを提供します。",
        liquidFeauresDescription7: "ジャスト・イン・タイム・デリバリー",
        liquidFeauresDescription8: "私たちのロジスティクスは、タイムリーかつ安全な方法で液体アルミニウムを供給するよう設計されており、お客様の生産スケジュールに適応し、産業プロセスの継続性を保証します。",
        liquidBenefitsTitle: "メリット",
        liquidBenefitsDescription1: "最終製品の品質最適化",
        liquidBenefitsDescription2: "当社の液体アルミニウムの高純度と一貫性のおかげで、製造された部品は、より優れた機械的特性、より高い強度、優れた仕上げを持ち、再加工の必要性を減らし、生産効率を向上させます。",
        liquidBenefitsDescription3: "生産コスト削減",
        liquidBenefitsDescription4: "高品質の液体アルミニウムを提供することで、エキアルムは鋳造工程における欠陥を最小限に抑え、スクラップ、不合格品、再加工に関連するコストを削減し、プロジェクトの収益性を最適化します。",
        liquidBenefitsDescription5: "産業用途における汎用性",
        liquidBenefitsDescription6: "当社のリキッドアルミニウムは、さまざまなプロセスや生産要件に適応する能力により、自動車から機械製造、電子部品まで、さまざまな産業分野に適しています。",
        liquidBenefitsDescription7: "エネルギー効率への貢献",
        liquidBenefitsDescription8: "液体アルミニウムの使用は、鋳造工程のサイクルタイムを短縮し、エネルギー消費を最適化し、より持続可能な生産とカーボンフットプリントの削減に貢献する。",

        /* Scrap - Product */
        scrapTitle: "スクラップ：産業の効率性と持続可能性",
        scrapDescription: "アルミニウムスクラップは、プロセスを最適化し、循環経済に貢献しようとする産業にとって不可欠な資源です。エクイリアムでは、管理された供給源と厳格な工業プロセスから得られる高品質のアルミニウムスクラップを専門に提供しています。この再生材料は、生産コストを削減するだけでなく、バージンアルミニウムに比べて処理に必要なエネルギーが少ないため、環境への影響も大幅に削減します。",
        scrapFeauresTitle: "卓越した機能",
        scrapFeauresDescription1: "一貫して管理された純度",
        scrapFeauresDescription2: "当社のアルミニウムスクラップは、徹底的な選別・分類工程を経ており、様々な産業用途での再利用に理想的な、高純度で均質な材料を保証しています。",
        scrapFeauresDescription3: "種類と形式の多様性",
        scrapFeauresDescription4: "当社は、お客様や各工程のニーズに合わせて、シート、切断屑、削り屑など、さまざまな形態のスクラップを提供しています。",
        scrapFeauresDescription5: "持続可能性への取り組み",
        scrapFeauresDescription6: "エクイアルムのアルミスクラップは、アルミのリサイクルが一次アルミの生産に必要なエネルギーのわずか5％しか消費しないため、カーボンフットプリントの削減に貢献します。",
        scrapFeauresDescription7: "サプライチェーンの効率化",
        scrapFeauresDescription8: "当社の経験とロジスティック・ネットワークにより、アルミスクラップの確実で時間厳守の供給が保証され、お客様の生産工程の継続性が維持されます。",
        scrapBenefitsTitle: "メリット",
        scrapBenefitsDescription1: "営業コストの削減",
        scrapBenefitsDescription2: "アルミスクラップを使用することで、企業は原材料コストを大幅に削減し、事業の財務効率を最適化することができる。",
        scrapBenefitsDescription3: "産業用途における汎用性",
        scrapBenefitsDescription4: "アルミスクラップは非常に汎用性が高く、元のアルミの特性を損なうことなく、自動車から電子機器、建築まで幅広い産業に適しています。",
        scrapBenefitsDescription5: "サーキュラー・エコノミーへの貢献",
        scrapBenefitsDescription6: "アルミニウム・スクラップを選択することで、企業は循環型経済に積極的に参加し、持続可能で環境に責任のある慣行を促進する。",
        scrapBenefitsDescription7: "最終製品の高い品質",
        scrapBenefitsDescription8: "スクラップ・アルミはリサイクルされるにもかかわらず、強度、軽さ、導電性といったアルミの基本特性を保持し、最終製品の品質を保証します。",

        /* Innovation - Product */
        innovationTitle: "未来を動かすイノベーション",
        innovationDescription1: "エクイアルムでは、革新こそが成長と継続的改善の原動力です。私たちは、アルミニウム業界の最前線にいることを誇りに思い、お客様に高品質の製品とカスタマイズされたソリューションをお届けできるよう、高度な技術とプロセスに投資しています。",
        innovationDescription2: "当社は、世界有数のテクノロジー産業から導入した最先端の機械設備を取り入れています。この設備により、鋳造工程を最適化し、業務の効率、精度、持続可能性を向上させることができます。このような技術への投資のおかげで、最高の国際基準を満たす製品を提供することができるのです。",
        innovationDescription3: "エクイリアムのイノベーションはテクノロジーだけにとどまらず、業務慣行やお客様との関わり方にも及んでいます。私たちは、より機敏に、変化する市場のニーズに迅速に対応できるよう、新しい方法論やアプローチを採用し、常にプロセスを改善することに注力しています。",
        innovation1: "最先端技術",
        innovation2: "継続的プロセス改善",
        innovation3: "卓越性へのコミットメント",

        /* Appointment */
        appointments: "連絡先",
        appointmentDescription1: "私たちの専門家へのアポイントメントを要求する",
        appointmentDescription2: "EQUIALUMにアポイントメントを取り、個別のアドバイスを受け、当社のアルミニウム製品がお客様の具体的なニーズにどのようにお応えできるかをご確認ください。",
        yourName: "お名前",
        yourEmail: "メールアドレス",
        yourPhone: "携帯電話",
        typeOfService: "サービスの種類",
        messages: "メッセージ",
        takeAppointment: "連絡先",

        /* Team */
        teamTitle: "生産センター・オブ・エクセレンス",
        teamDescription: "エクイアルムは、グアダラハラとアグアスカリエンテスに近代的な工場を有し、効率的で高品質なアルミニウム生産を保証する最先端技術を備えています。これらの施設は戦略的に配置されており、機敏な物流を促進し、持続可能性と革新への確固としたコミットメントを維持しながら、お客様の需要に迅速に対応することを可能にしています。",
        guadalajara: "Guadalajara",
        plant1: "生産工場 l",
        aguascalientes: "Aguascalientes",
        plant2: "生産工場 ll",
        comingSoon: "近日公開",
        plant3: "生産工場 lll",

        /* Testimonial */
        testimonialTitle: "細部に至るまで卓越",
        testimonialDescription1: "エクイアルムの卓越した品質とサービスをお客様がどのように体験されたかをご覧ください。お客様の声は、エクイリアムの卓越性と総合的な満足度に対するコミットメントを浮き彫りにしています。",
        more100: "100+",
        happyCustomers: "幸せな顧客",
        fulfilledProjects: "完了したプロジェクト", 
        none: "",
        nameOfCustomer1: "クライアント名",
        profession1: "職業",
        none: "",
        nameOfCustomer2: "クライアント名",
        profession2: "職業",

        /* Footer */
        footerDescription: "エクイアルムはアルミニウム製品の販売におけるリーディングカンパニーであり、インゴット、バー、コーン、液体、スクラップを提供している。",
        footerDescription1: "最高品質のアルミニウム製品をお求めなら、ぜひ当社にご連絡ください。",
        address: "住所",
        streetGdl: "123 Calle, Guadalajara, MX",
        numerPhone: "+52 33 1144 4819",
        emailCompany: "alejandro.garcia@equialum.mx",
        quickLinks: "クイックリンク",
        termsAndConditions: "ご利用条件",
        politicAndPrivate: "プライバシーポリシー",
        contactanos: "お問い合わせ",
        contacto: "連絡先",
        call: "電話番号: +52 33 1144 4819",
        usEmail: "Eメールアドレス: alejandro.garcia@equialum.mx",
        contactTitle: "EQUIALUMに接続し、パーソナライズされた支援を受ける",
        contactSubTitle: "私たちがお手伝いします！",
        contactDetails: "連絡先",
        contactData1: "高度な技術と高い生産能力で高品質のアルミニウムを生産",
        contactData2: "アルミニウム生産における革新と効率化、工程と品質の最適化。",
        contactDescription: "EQUIALUMでは、お客様のニーズやお問い合わせに対応いたします。当社の製品、サービス、または一般的な情報についてのご質問は、ご遠慮なくお問い合わせください。お電話、Eメール、オンラインフォームからお問い合わせください。また、当社のソーシャルメディア・チャンネルを通じて、当社の最新ニュースや更新情報をお知らせすることも可能です。お客様の満足を第一に考え、最高のサービスを提供することをお約束いたします。",
    }
    // Añade más idiomas y traducciones si es necesario
};

function setLanguage(lang) {
    localStorage.setItem('language', lang); // Guardar idioma en LocalStorage
    const elements = document.querySelectorAll('[data-translate-key]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate-key');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLanguage = localStorage.getItem('language') || 'es'; // Idioma por defecto es 'es' osease español
    setLanguage(savedLanguage);
});